repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    - id: mypy
      additional_dependencies: [types-requests==2.26.0]
default_language_version:
    python: python
