repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.750'
    hooks:
    - id: mypy
default_language_version:
    python: python