repos:
-   repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3
-   repo: local
    hooks:
    - id: ty
      name: ty
      entry: uv run --group lint ty check .
      language: system
      pass_filenames: false
default_language_version:
    python: python3.14
