version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ddw"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jdq32m7bbjhg"
s3_prefix = "ddw"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
