# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  sam: circleci/aws-sam-serverless@2.1.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8.7

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./.venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  unit-tests:
    docker:
      - image: circleci/python:3.8.7

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: run tests
          command: |
            . .venv/bin/activate
            pytest --junitxml=test-reports/pytest/junit.xml

      - store_test_results:
          path: test-reports
  mypy:
    docker:
      - image: circleci/python:3.8.7

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install mypy

      - run:
          name: run mypy
          command: |
            . .venv/bin/activate
            mypy --ignore-missing-imports --scripts-are-modules --junit-xml test-reports/mypy/junit.xml ddw

      - store_test_results:
          path: test-reports

  black:
    docker:
      - image: circleci/python:3.8.7

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install black

      - run:
          name: run black
          command: |
            . .venv/bin/activate
            black --check .

  deploy:
    docker:
      - image: circleci/python:3.8.7
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - sam/install
      - sam/build:
          template: template.yaml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-jdq32m7bbjhg
          validate: false
          use-container: false
      - sam/deploy:
          stack-name: ddw
          template: template.yaml

workflows:
  version: 2
  tests:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - mypy:
          requires:
            - build
      - black:
          requires:
            - build
      - deploy:
          requires:
            - unit-tests
            - mypy
            - black
