# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  unit-tests:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --junitxml=test-reports/pytest/junit.xml

      - store_test_results:
          path: test-reports
  mypy:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install mypy

      - run:
          name: run mypy
          command: |
            . venv/bin/activate
            mypy --ignore-missing-imports --scripts-are-modules --junit-xml test-reports/mypy/junit.xml

      - store_test_results:
          path: test-reports

workflows:
  version: 2
  tests:
    jobs:
      - unit-tests
      - mypy
