# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.4

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "requirements.txt" }}-{{ checksum
              "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./.venv
          key: v4-dependencies-{{ checksum "requirements.txt" }}-{{ checksum
            "requirements-dev.txt" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  unit-tests:
    docker:
      - image: cimg/python:3.11.4

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: run tests
          command: |
            . .venv/bin/activate
            pytest --junitxml=test-reports/pytest/junit.xml

      - store_test_results:
          path: test-reports
  mypy:
    docker:
      - image: cimg/python:3.11.4

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install "mypy==1.5.1" "types-requests==2.31.0"

      - run:
          name: run mypy
          command: |
            . .venv/bin/activate
            mypy --ignore-missing-imports --scripts-are-modules --junit-xml test-reports/mypy/junit.xml ddw

      - store_test_results:
          path: test-reports

  black:
    docker:
      - image: cimg/python:3.11.4

    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install black

      - run:
          name: run black
          command: |
            . .venv/bin/activate
            black --check .


  build-docker:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/
      - run:
        name: configure and run buildx
        command: |
          docker buildx create --use
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8 --tag galonsky/diddukewin:latest .
workflows:
  version: 2
  tests:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - mypy:
          requires:
            - build
      - black:
          requires:
            - build
      - build-docker:
          requires:
            - unit-tests
            - mypy
            - black
          filters:
            branches:
              only: master
